### PR TITLE
Jassbot beta

### PR DESCRIPTION
**Pull request by lep**
This adds search functionality for all toplevel constructs and not just natives and functions. Not optimized at all it doesn't seem to be stressed.

A code cleanup would be wise later.

### CODE REVIEW

**Comment by Luashine** [comment]
Hey lep, this is a **great** improvement to the previous search! Almost entirely eliminates the need to peek into the source files. I wanted to voice my ideas for a versatile search as if it were a blank slate, I hope you are ready to hear it :)

Uh I unloaded a lot of stuff here again, feel free to move this into separate issues where appropriate and I remove the parts from this comment.

The overkill example: poe.trade
---
*See screenshot at the bottom* https://web.archive.org/web/20221013101102/http://poe.trade/

I had used it back in the day, this website searched all possible items in Path Of Exile. The item system there had many facets, randomly rolled modifiers and stats. Most of the time you didn't need to use the features but rarely you would filter however you liked. Especially the "mods" selector that allowed you to specify **if/and/not/count/sum/weight** of the mods. I think the web archive doesn't show the UI of the AND/IF buttons to the left. 

For the purposes of Jassdoc, I think this could serve as an eventual GUI wizard to search queries. Although I don't imply that the search query system would become this complicated.

Query Suggestions
---

A ~~new~~ extended structure:

1. (without a specifier): exact match by name. Multiple values are an AND filter to previous match (space separated)
    - it makes sense to include literal search for function names, global variable names and type names here
    - query "player red" does not return PLAYER_COLOR_RED constant in current beta. I actually wanted to filter for unit item drop/pickup events and it would not find anything. And I didn't know exactly their names. "event_un" returns all "EVENT_UNIT_*" currently but "event_uni" returns nothing!
3. specifier TYPE: limits search to only include this type. `function / global || variable / type`. I don't think there should be a difference for "native vs blizzard.j func" it'd be confusing to use
    - works well now. it serves both as a type search and "used as / returned by" search which is actually good
    - `type playercolor` after ~20 results returns `constant native GetBJMaxPlayers takes nothing returns integer` that has nothing to do with it etc.
5. specifier TAKES: exists, AND relationship for multiple values
    - `takes player, player` doesn't work, but imho this is the natural (intuitive) syntax similar to how functions are declared.
    - `takes player player` correctly returns all double `player` functions at the beginning. Then it proceeds with singular `player` argument which is alright
7. specifier RETURNS: exists
    - currently a single value and works well. What about allowing multi values in cases you forgot the exact return? I guess it'd only be useful for `return real, integer` = OR relationship.
9. specifier CATEGORY: tbd
    - Categories would be first populated by WE GUI Trigger categories but I thought it'd be nice to have custom categories too, to avoid exhaustive "`@note` See: ..." cross-linking. It'd simply return all items belonging to a category. One function can be in multiple categories.
11. specifier FROM: tbd, maybe it would be part of CATEGORY. Like common.ai, common.j, blizzard.j etc.

Description Search
---

Another open-ended question, description search? I imagine and hope that with the integration of GUI descriptions and names, more people would be using Jassdoc. For now the interest is luke warm at best. This functionality would become a much needed bridge between the Jass code and GUI worlds, like now I have no idea what people's GUI screenshots are doing under the hood and those only using GUI triggers are too afraid to start in Jass code land because it's so disconnected and they would need to start from scratch.

I don't think it'd be appropriate to mix this with the current, precise name search. Either a new keyword (unwieldy) or a checkbox under the input to kinda permanently enable description search for a user.

I do NOT think this should be considered yet, if WE name search is implemented. This idea should be assessed later based on what users think.

Source coloring
---

See [screenshot](https://www.hiveworkshop.com/data/ratory-images/271/271282-ed106ade19f1c9ee798f32b82e9a3764.png) from my [N++ highlighter](https://www.hiveworkshop.com/threads/notepad-jass-vjass-syntax-highlighter-2023-v8.341147/).

Currently all links are the same color. One idea was to prefix each result with an icon to show where the func is coming from (AI/BLZ/Native) because now, mostly common.ai results, are confusing. You don't want to use them most of the time.

I don't like the icon approach too much, so what about coloring the actual links a different color based on source? Just a custom ID in HTML and set the color in CSS. Because I followed the Obsidian theme in N++ here's my current palette:

- type: light blue, bold
- native: blue / deep blue
- common.ai: short-coming and I couldn't customize it, light-green
- Blizzard.j globals: low saturation red
- Blizzard.j functions: pink
- Game natives in common.j: lavender (purle-ish)

Finally disable :visited color distinction, because it's actually useless here.

Cleaning up the output
---

https://lep.duckdns.org/beta/jassbot/doc/GetBJMaxPlayers

1. Title, func name
2. Comment
3. note(s)
4. patch
5. return type
6. source code
7. source (link to jassdoc github source line)
8. wc3modding link

- return type is redundant, especially placed right above the actual source declaration
- patch should be moved under source code, rarely needed
- wc3modding link should be merged into source: "Source: common.j (web, [jassdoc source](https://github.com/lep/jassdoc/blob/01193d480d29e0c01e75fd69f638c2222377cbd0/common.j#L1768)), [wc3modding.com](https://wc3modding.info/pages/jass-documentation-database/class/functions/query/GetBJMaxPlayers/)" where web is the sort-of pretty render of the Jassdoc source file.

HTML Render
---

Separately: add an HTML render of the jassdoc source files, because Github's preview is laggy and unusable on mobile. I almost can't scroll side ways on Firefox Android. They also added a custom CTRL-F functionality to cope with inability to render the whole file with syntax highlighting at once!

The PoE trade search screenshot
---

poe-trade

**Comment by lep** [comment]
Thanks for the report. Some nice ideas. I'm still not too happy with the current
state but i think i didn't break the old flow too much and added the long wanted
search for globals and such.

Now to go into explicit points raised:

> (without a specifier): exact match by name. Multiple values are an AND filter to previous match (space separated)
> - it makes sense to include literal search for function names, global variable names and type names here

You are generally correct but here's the UX i wanted to provdide which i can see
from the logs would be good to have: users often simply type in the type into the
searchbar, that is something like `gamedifficulty`. Searching only for names,
including globals, this would not return functions that take or return a `gamedifficulty`.
But i think it should, that's why i create multiple queries for certain inputs.

That brings me to my next point, which is that i don't really like programming
user interfaces. So i would rather have it all available through the textbox.
Your idea of stacking filters on top of each other is of course a good one, and
basically how the old jassbot search worked. And it's also still how the beta
jassbot works except that we do possibly multiple parallel searches like
described above.

Also having specifier like `global` or `type` creates these parallel searches
aswell as you could just be searching for a thing which has `type` in its name.
Of course a richer interface could ease these problems.

> query "player red" does not return PLAYER_COLOR_RED constant in current beta.

Yes. Intent is hard. This *structure* has multiple possible search queries, that is

  1. function which takes two types (one would even be corect)
  2. a global player variable named something red

Maybe i could simply introduce another query aswell which just concats all
words and searches by name.

> I actually wanted to filter for unit item drop/pickup events and it would not find anything. And I didn't know exactly their names. "event_un" returns all "EVENT_UNIT_*" currently but "event_uni" returns nothing!

Yes, im aware. But i haven't looked to deeply into it to know why that is happening.

> `type playercolor` after ~20 results returns `constant native GetBJMaxPlayers takes nothing returns integer` that has nothing to do with it etc.

Yes, this is a consequence of the multiple constructed queries. The better query
constructed is of course the type query but it's also parsed as search via
parameters, so functions that take a `type` and a `playcolor`. `type` is fuzzily
matched to the best real type (idk which this is in practice). Or maybe even
another query. Why exactly that native is returned i don't know w/o looking more
into it. My goal is to print the "correct" result first which it does and then
i don't care too much about "nonsense" after that.

> takes player, player doesn't work, but imho this is the natural (intuitive) syntax similar to how functions are declared.

Yes, i'm aware. Just needs a simple fix in the parser. Shouldn't be too hard.

> currently a single value and works well. What about allowing multi values in cases you forgot the exact return? I guess it'd only be useful for return real, integer = OR relationship.

Technically possible (i guess) but this would create quadratically many queries
(in the current implementation). I have to at least think a bit about performance
as the algorithms i use are inherently quadratic. So far even modest computers
are fast enough to chuck through my suboptimal code but i cannot stack too many
of these on top of each other.
Do note though that i have allready included a subtype relationship for reals and integers.

> specifier CATEGORY: tbd
> Categories would be first populated by WE GUI Trigger categories but I thought it'd be nice to have custom categories too, to avoid exhaustive "@note See: ..." cross-linking. It'd simply return all items belonging to a category. One function can be in multiple categories.

Yes i have thought about that aswell and it would be nice. But here comes another
problem into play: that stuff lives inside the sqlite file and jassbot works
on .j files alone. I would **love** to base jassbot ontop of sqlite (via extension functions, for example).

Of course you could simply just not query jassbot when you encode an `@annotation` query, but it would be a different project then.
This basically ties into your point `Description Search`.


> Source coloring

I would like to keep the current colorscheme because it has history (wc3c, tesh, old hive).
We could add some indicator behind each link depending on what it is. Maybe something from [here](https://icons.getbootstrap.com/) for example.

> Cleaning up the output

Fine i guess. More of a [jassbot-bp](https://github.com/lep/jassbot-bp) issue though. See also <https://github.com/lep/jassbot-bp/issues/2>.

> HTML Render

Probably a good idea but it has to be kept in sync, etc. So maybe not top priority. Also i could link to my cgit instance instead/aswell as to github.

**Comment by Luashine** [comment]
> Allow 

Did you forget to push the update or does it not work?

OK space https://lep.duckdns.org/beta/jassbot/search?query=takes%20unit%20integer
NO RESULTS comma https://lep.duckdns.org/beta/jassbot/search?query=takes%20unit,%20integer

Ah here it has results https://lep.duckdns.org/beta/jassbot/search?query=order%20takes%20unit%20string

---

> Also having specifier like global or type creates these parallel searches aswell as you could just be searching for a thing which has type in its name.

I didn't think of it. Parallel searches or more complexity? Like literal Google syntax of `"word"`

---

> users often simply type in the type into the searchbar, that is something like gamedifficulty

fair. My proposal I forgot to voice, is to add an **explanation of the search query** right under the input box. So it would verbalize the typed query in human language and help learning the interface. This makes it very text-centric ;)

Example search: "order takes unit string"
Explanation: "Function named 'order' with arguments of type 'unit' *and* 'string' "

If parallel ambiguous search must be run, second search is added on next line etc.

----

> quadratically many queries (in the current implementation).
> I would love to base jassbot ontop of sqlite 

Oh I didnt know

---

>> Source coloring
> I would like to keep the current colorscheme because it has history (wc3c, tesh, old hive).

Oh I actually intended this for the search results only, not the source code itself. I dont care about syntax highlighting much and B.j functions are short enough to understand. Mainly to help distinguish the different source files. I think a **colored** icon would do too. There are not many fitting icons under that link, but I can choose a few.

If we go with the icons, my idea is to place them to the left of the result line. Ideally as ::before kind, so it remains unselectable. Still distinct colors for at least per file: common.j common.ai blizzard.j. If this sounds OK, I will look at the icon list again.

---

> HTML Render
> Probably a good idea but it has to be kept in sync, etc. So maybe not top priority.

What if I make a simple (Lua) script and let it generate Github Pages using Github Actions? My intent was to keep it very simple anyway. Or whatever language that's like a first-class citizen with those Action containers with a working SQLite binding.

**Comment by lep** [comment]
> > Allow
> 
> Did you forget to push the update or does it not work?
> 
> OK space https://lep.duckdns.org/beta/jassbot/search?query=takes%20unit%20integer NO RESULTS comma https://lep.duckdns.org/beta/jassbot/search?query=takes%20unit,%20integer
> 
> Ah here it has results https://lep.duckdns.org/beta/jassbot/search?query=order%20takes%20unit%20string

Should be fixed now.



> > users often simply type in the type into the searchbar, that is something like gamedifficulty
> 
> fair. My proposal I forgot to voice, is to add an **explanation of the search query** right under the input box. So it would verbalize the typed query in human language and help learning the interface. This makes it very text-centric ;)
> 
> Example search: "order takes unit string" Explanation: "Function named 'order' with arguments of type 'unit' _and_ 'string' "
> 
> If parallel ambiguous search must be run, second search is added on next line etc.

Yeah i had that idea aswell. But i just don't really like doing web design. I added it for now but it's probably not quite in the way you would've wanted it to be. Could change in the future.




> > > Source coloring
> > > I would like to keep the current colorscheme because it has history (wc3c, tesh, old hive).
> 
> Oh I actually intended this for the search results only, not the source code itself. I dont care about syntax highlighting much and B.j functions are short enough to understand. Mainly to help distinguish the different source files. I think a **colored** icon would do too. There are not many fitting icons under that link, but I can choose a few.
> 
> If we go with the icons, my idea is to place them to the left of the result line. Ideally as ::before kind, so it remains unselectable. Still distinct colors for at least per file: common.j common.ai blizzard.j. If this sounds OK, I will look at the icon list again.

Yes, using `:before` or `:after` would be the preferred way. Icon doesn't have to be from that list. Just inspiration. Maybe i will get specific icons made.

> > HTML Render
> > Probably a good idea but it has to be kept in sync, etc. So maybe not top priority.
> 
> What if I make a simple (Lua) script and let it generate Github Pages using Github Actions? My intent was to keep it very simple anyway. Or whatever language that's like a first-class citizen with those Action containers with a working SQLite binding.

Maybe. Allthough it makes more sense to not use the db in that case as it's easier to colour the input file than to reconstruct it from the DB.

**Pull request merged**
